CANDIDATES_SHEET_ID = '1XQONns4-Dq3mS3Wxb5168TIhvR2qPC-E1Wm-0eUDnqk'
CANDIDATES_SHEET_RANGE = "'Sheet1'!A2:c17"

MATCHES_SHEET_ID = '1-VM9FuGW3kBVZtT6TWbKL_WuR6GtRpp2_MznoUwRaQg'
MATCHES_SHEET_RANGE = "A2:C3"

ALLOCATIONS_SHEET_ID = '1UzBzZ3ZloqpRDQ_IWdmRTBdzxOdn0gFbeSwQ87uXvEU'
ALLOCATIONS_GET_SHEET_RANGE_POSTFIX = 'A4:E18'

MATCH_RESULTS_SHEET_ID = '1Z9M-tq03Fwzylagl8HFNSHHDZJNtIe0ebneFTo_f5rA'
MATCH_RESULTS_SHEET_RANGE_POSTFIX = "!A3:D24"

CANDIDATE_RESULTS_SHEET_ID = '1bEkz61QgoY_LGKMPbF_14LqPBBhh1f4y88ViqAXVMVE'


RUN_POINTS = 1
WICKET_POINTS = 20



