CANDIDATES_SHEET_ID = '1XQONns4-Dq3mS3Wxb5168TIhvR2qPC-E1Wm-0eUDnqk'
CANDIDATES_SHEET_RANGE = "'Sheet1'!A2:c16"

MATCHES_SHEET_ID = '1-VM9FuGW3kBVZtT6TWbKL_WuR6GtRpp2_MznoUwRaQg'
MATCHES_SHEET_RANGE = "A2:C3"

ALLOCATIONS_SHEET_ID = '1UzBzZ3ZloqpRDQ_IWdmRTBdzxOdn0gFbeSwQ87uXvEU'


